--============================================--
/*       1. LIMPIEZA: Borrado de objetos      */
--============================================--
DROP TABLE PAIS CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE MECANICO CASCADE CONSTRAINTS;
DROP TABLE SERVICIO CASCADE CONSTRAINTS;
DROP TABLE MANTENCION CASCADE CONSTRAINTS;
DROP TABLE DETALLE_SERVICIO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_SERVICIO;
DROP SEQUENCE SEQ_CIUDAD;

--====================================================--
/*                 2. TABLAS FUERTES                  */
--====================================================--

/*-------------------- PAIS --------------------*/
CREATE TABLE PAIS (
    id_pais NUMBER(3) GENERATED BY DEFAULT AS IDENTITY (START WITH 9 INCREMENT BY 3),
    nom_pais VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_PAIS PRIMARY KEY (id_pais)
);

/*-------------------- CIUDAD --------------------*/
CREATE TABLE CIUDAD (
    id_ciudad NUMBER(3),
    nom_ciudad VARCHAR2(30) NOT NULL,
    cod_pais NUMBER(3) NOT NULL,
    CONSTRAINT PK_CIUDAD PRIMARY KEY (id_ciudad),
    CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY (cod_pais)
        REFERENCES PAIS(id_pais)
);

/*-------------------- SUCURSAL --------------------*/
CREATE TABLE SUCURSAL (
    id_sucursal CHAR(3),
    nom_sucursal VARCHAR2(20) NOT NULL,
    calle VARCHAR2(20),
    num_calle NUMBER(4),
    cod_ciudad NUMBER(3) NOT NULL,
    CONSTRAINT PK_SUCURSAL PRIMARY KEY (id_sucursal),
    CONSTRAINT FK_SUCURSAL_CIUDAD FOREIGN KEY (cod_ciudad)
        REFERENCES CIUDAD(id_ciudad)
);

/*-------------------- MECANICO --------------------*/
CREATE TABLE MECANICO (
    cod_mecanico NUMBER(5) GENERATED BY DEFAULT AS IDENTITY (START WITH 460 INCREMENT BY 7),
    pnombre VARCHAR2(20) NOT NULL,
    snombre VARCHAR2(20),
    apaterno VARCHAR2(20) NOT NULL,
    amaterno VARCHAR2(20),
    bono_jefatura NUMBER(10),
    sueldo NUMBER(10) NOT NULL,
    monto_impuestos NUMBER(10),
    cod_supervisor NUMBER(5),
    CONSTRAINT PK_MECANICO PRIMARY KEY (cod_mecanico),
    CONSTRAINT FK_MECANICO_SUP FOREIGN KEY (cod_supervisor)
        REFERENCES MECANICO(cod_mecanico)
);

/*-------------------- SERVICIO --------------------*/
CREATE TABLE SERVICIO (
    id_servicio NUMBER(3),
    descripcion VARCHAR2(100) NOT NULL,
    costo NUMBER(7) NOT NULL,
    CONSTRAINT PK_SERVICIO PRIMARY KEY (id_servicio)
);

--====================================================--
/*              3. TABLAS DEPENDIENTES                */
--====================================================--

/*-------------------- MANTENCION --------------------*/
CREATE TABLE MANTENCION (
    num_mantencion NUMBER(4),
    cod_sucursal CHAR(3) NOT NULL,
    fecha_ingreso DATE,
    fecha_salida DATE,
    patente_auto CHAR(8),
    cod_mecanico NUMBER(5) NOT NULL,
    costo_total NUMBER(10),
    estado VARCHAR2(15),
    CONSTRAINT PK_MANTENCION PRIMARY KEY (num_mantencion),
    CONSTRAINT FK_MANT_MEC FOREIGN KEY (cod_mecanico)
        REFERENCES MECANICO(cod_mecanico),
    CONSTRAINT FK_MANT_SUC FOREIGN KEY (cod_sucursal)
        REFERENCES SUCURSAL(id_sucursal)
);

/*-------------------- DETALLE_SERVICIO --------------------*/
CREATE TABLE DETALLE_SERVICIO (
    mantencion_num NUMBER(4),
    cod_servicio NUMBER(3),
    descripcion_serv NUMBER(4),
    cantidad NUMBER(3),
    CONSTRAINT PK_DETALLE_SERV PRIMARY KEY (mantencion_num, cod_servicio),
    CONSTRAINT FK_DET_MANT FOREIGN KEY (mantencion_num)
        REFERENCES MANTENCION(num_mantencion),
    CONSTRAINT FK_DET_SERV FOREIGN KEY (cod_servicio)
        REFERENCES SERVICIO(id_servicio)
);

/*-------------------- CLIENTE --------------------*/
CREATE TABLE CLIENTE (
    rut NUMBER(8),
    dv_cliente CHAR(1) NOT NULL,
    pnombre VARCHAR2(20) NOT NULL,
    snombre VARCHAR2(20),
    apaterno VARCHAR2(20) NOT NULL,
    amaterno VARCHAR2(20),
    telefono VARCHAR2(12),
    email VARCHAR2(40),
    tipo_cli CHAR(1),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (rut)
);

--====================================================--
/*                 4. MODIFICACIONES                  */
--====================================================--

/* 1. Eliminar costo_total */
ALTER TABLE MANTENCION DROP COLUMN costo_total;

/* 2. Modificar PK MANTENCION */
ALTER TABLE DETALLE_SERVICIO DROP CONSTRAINT FK_DET_MANT;
ALTER TABLE MANTENCION DROP CONSTRAINT PK_MANTENCION;

ALTER TABLE MANTENCION
ADD CONSTRAINT PK_MANTENCION 
PRIMARY KEY (num_mantencion, cod_sucursal);

ALTER TABLE DETALLE_SERVICIO
ADD cod_sucursal CHAR(3);

ALTER TABLE DETALLE_SERVICIO
ADD CONSTRAINT FK_DET_MANT
FOREIGN KEY (mantencion_num, cod_sucursal)
REFERENCES MANTENCION(num_mantencion, cod_sucursal);

/* 3. Email único */
ALTER TABLE CLIENTE
ADD CONSTRAINT UN_CLIENTE_EMAIL UNIQUE (email);

/* 4. CHECK DV */
ALTER TABLE CLIENTE
ADD CONSTRAINT CK_CLIENTE_DV_CLIENTE
CHECK (dv_cliente IN ('0','1','2','3','4','5','6','7','8','9','K'));

/* 5. CHECK sueldo */
ALTER TABLE MECANICO
ADD CONSTRAINT CK_MECANICO_SUELDO
CHECK (sueldo >= 510000);

/* 6. CHECK estado */
ALTER TABLE MANTENCION
ADD CONSTRAINT CK_MANTENCION_ESTADO
CHECK (estado IN ('Reserva','Ingresado','Entregado','Anulado'));

/*================ SECUENCIAS =================*/

/* SERVICIO */
CREATE SEQUENCE SEQ_SERVICIO
START WITH 400 INCREMENT BY 2;

/* CIUDAD */
CREATE SEQUENCE SEQ_CIUDAD
START WITH 165 INCREMENT BY 5;

/*================ POBLAR PAIS =================*/
INSERT INTO PAIS (nom_pais) VALUES ('Chile');
INSERT INTO PAIS (nom_pais) VALUES ('Peru');
INSERT INTO PAIS (nom_pais) VALUES ('Colombia');

/*================ POBLAR CIUDAD =================*/
INSERT INTO CIUDAD VALUES (SEQ_CIUDAD.NEXTVAL, 'Santiago', 9);
INSERT INTO CIUDAD VALUES (SEQ_CIUDAD.NEXTVAL, 'Lima', 12);
INSERT INTO CIUDAD VALUES (SEQ_CIUDAD.NEXTVAL, 'Bogota', 15);

/*================ POBLAR SUCURSAL =================*/
INSERT INTO SUCURSAL VALUES ('S01','Providencia','Av. A. Varas',234,165);
INSERT INTO SUCURSAL VALUES ('S02','Las 4 esquinas','Av. Latina',669,170);
INSERT INTO SUCURSAL VALUES ('S03','El Cafetero','Av. El Faro',900,175);

/*================ POBLAR MECANICO =================*/
INSERT INTO MECANICO 
(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Jorge', 'Pablo', 'Soto', 'Sierpe', 5400000, 2759000, 223580, NULL);

INSERT INTO MECANICO 
(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Pedro', 'Jose', 'Manriquez', 'Corral', NULL, 759000, 23980, NULL);

INSERT INTO MECANICO 
(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Sandra', 'Josefa', 'Letelier', 'S.', 0, 659000, 22358, 460);

INSERT INTO MECANICO 
(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Felipe', 'M.', 'Vidal', 'A.', NULL, 759000, 23580, 460);

INSERT INTO MECANICO 
(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Jose', 'Miguel', 'Troncoso', 'B.', NULL, 659000, 44580, 474);

INSERT INTO MECANICO 
(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Juan', 'Pablo', 'Sánchez', 'R.', NULL, 859000, 23380, 474);

INSERT INTO MECANICO 
(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Carlos', 'Felipe', 'Soto', 'J.', 0, 597000, 23580, 474);

INSERT INTO MECANICO 
(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Alberto', 'P.', 'Cerda', 'Ramírez', NULL, 559000, 22380, 460);

INSERT INTO MECANICO 
(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Alejandra', 'Gabriela', 'Infanti', 'R.', NULL, 659000, 22380, 460);

INSERT INTO MECANICO 
(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Roberto', 'Patricio', 'Gutierrez', 'Sosa', NULL, 859000, 22380, 460);

/*================ POBLAR SERVICIO =================*/
INSERT INTO SERVICIO VALUES (SEQ_SERVICIO.NEXTVAL,'Cambio Luces',45000);
INSERT INTO SERVICIO VALUES (SEQ_SERVICIO.NEXTVAL,'Desabolladura',67000);
INSERT INTO SERVICIO VALUES (SEQ_SERVICIO.NEXTVAL,'Revision Frenos',30000);
INSERT INTO SERVICIO VALUES (SEQ_SERVICIO.NEXTVAL,'Cambio Puerta Trasera',50000);

/*================ POBLAR MANTENCION =================*/
INSERT INTO MANTENCION
(num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (101, 'S01', TO_DATE('12-04-2023', 'DD-MM-YYYY'), NULL, NULL, 481, 'Reserva');

INSERT INTO MANTENCION
(num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (102, 'S02', TO_DATE('21-02-2023', 'DD-MM-YYYY'), TO_DATE('21-02-2023', 'DD-MM-YYYY'), NULL, 502, 'Entregado');

INSERT INTO MANTENCION
(num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (103, 'S02', TO_DATE('09-10-2023','DD-MM-YYYY'), NULL, NULL, 502, 'Anulado');

INSERT INTO MANTENCION
(num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (104, 'S03', TO_DATE('11-08-2023','DD-MM-YYYY'), TO_DATE('18-08-2023','DD-MM-YYYY'), NULL, 509, 'Entregado');

INSERT INTO MANTENCION
(num_mantencion, cod_sucursal, fecha_ingreso, fecha_salida, patente_auto, cod_mecanico, estado)
VALUES (105, 'S03', TO_DATE('03-12-2023', 'DD-MM-YYYY'), NULL, NULL, 509, 'Ingresado');

--====================================================--
/* INFORME 1: SUELDOS DE LOS MECANICOS                */
--====================================================--

SELECT
    cod_mecanico AS "ID MECANICO",
    pnombre || ' ' || apaterno AS "NOMBRE MECANICO",
    sueldo AS "SALARIO",
    monto_impuestos AS "IMPUESTO ACTUAL",
    monto_impuestos * 0.8 AS "IMPUESTO REBAJADO",
    sueldo - (monto_impuestos * 0.8) AS "SUELDO CON REBAJA DE IMPUESTOS"
FROM MECANICO
WHERE bono_jefatura IS NULL AND monto_impuestos < 40000
ORDER BY monto_impuestos DESC, apaterno ASC;

--====================================================--
/* INFORME 2: AJUSTE SALARIAL                         */
--====================================================--
SELECT
    cod_mecanico AS "IDENTIFICADOR",
    pnombre || ' ' || snombre || ' ' || apaterno AS "NOMBRE MECANICO",
    sueldo AS "SALARIO ACTUAL",
    (sueldo * 0.05) AS "AJUSTE",
    (sueldo + (sueldo * 0.05)) AS "SUELDO_REAJUSTADO"
FROM MECANICO
WHERE sueldo BETWEEN 600000 AND 900000
    OR cod_supervisor IS NULL
ORDER BY sueldo ASC, pnombre || ' ' || snombre || ' ' || apaterno DESC;