---------------------------------------------------------------------------------------
UNDEFINE VALOR_MAXIMO;
UNDEFINE VALOR_MINIMO;

/*CASO 1: ANALISIS DE PROPIEDADES*/
SELECT
    NRO_PROPIEDAD AS "PROPIEDAD",
    
    UPPER(DIRECCION_PROPIEDAD) AS "DIRECCION",
    
    LPAD(REPLACE(TO_CHAR(VALOR_ARRIENDO, '$99,999,999'),',','.'),15) AS "ARRIENDO",
    
    LPAD(REPLACE(TO_CHAR(VALOR_GASTO_COMUN, '$99,999,999'),',','.'),15) AS "GGCC_ACTUAL",
    
    LPAD(REPLACE(TO_CHAR(ROUND(VALOR_GASTO_COMUN * 1.1), '$99,999,999'),',','.'),15) AS "GGCC_AJUSTADO",
    
    'Propiedad ubicada en comuna ' || (ID_COMUNA) AS "UBICACION"
    
FROM PROPIEDAD
WHERE ID_COMUNA IN (82, 84, 87) 
AND VALOR_ARRIENDO < &VALOR_MAXIMO
AND nro_dormitorios IS NOT NULL
ORDER BY VALOR_GASTO_COMUN ASC NULLS LAST, VALOR_ARRIENDO DESC;

---------------------------------------------------------------------------------------
/*CASO 2: ANALISIS DE ANTIGÜEDAD DE ARRIENDO*/
SELECT
    NRO_PROPIEDAD AS "Propiedad",    
    NUMRUT_CLI AS "Código Arrendatario",    
    LPAD(TO_CHAR(FECINI_ARRIENDO, 'dd.mon.yyyy'),25) AS "Fecha Inicio Arriendo",
    
    CASE
        WHEN FECTER_ARRIENDO IS NULL THEN 'PROPIEDAD ACTUALMENTE ARRENDADA'
        ELSE TO_CHAR(FECTER_ARRIENDO, 'dd.mon.yyyy')
    END AS "Fecha Término Arriendo",
    
    LPAD(REPLACE(TO_CHAR(ROUND(NVL(FECTER_ARRIENDO, SYSDATE) - FECINI_ARRIENDO), '9,999'),',','.'),15) AS "Días Arriendo" ,    
    FLOOR(MONTHS_BETWEEN(NVL(FECTER_ARRIENDO, SYSDATE), FECINI_ARRIENDO)/12) AS "Años Arriendo",
    
    LPAD(CASE
        WHEN FLOOR(MONTHS_BETWEEN(NVL(FECTER_ARRIENDO, SYSDATE), FECINI_ARRIENDO)/12) >= 10 THEN 'COMPROMISO DE VENTA'
        WHEN FLOOR(MONTHS_BETWEEN(NVL(FECTER_ARRIENDO, SYSDATE), FECINI_ARRIENDO)/12) BETWEEN 5 AND 9 THEN 'CLIENTE ANTIGUO'
        ELSE 'CLIENTE NUEVO'
    END,25) AS "Clasificación Estado"
    
FROM ARRIENDO_PROPIEDAD
WHERE (NVL(FECTER_ARRIENDO, SYSDATE) - FECINI_ARRIENDO) > &VALOR_MINIMO
ORDER BY "Días Arriendo" DESC;

---------------------------------------------------------------------------------------
/*CASO 3: ANALISIS DE ARRIENDO PROMEDIO POR TIPO DE PROPIEDAD*/
SELECT
    LPAD(ID_TIPO_PROPIEDAD,15) AS "TIPO PROPIEDAD",
    
    CASE
        WHEN ID_TIPO_PROPIEDAD = 'A' THEN 'Casa'
        WHEN ID_TIPO_PROPIEDAD = 'B' THEN 'Departamento'
        WHEN ID_TIPO_PROPIEDAD = 'C' THEN 'Local'
        WHEN ID_TIPO_PROPIEDAD = 'D' THEN 'Parcela sin casa'
        WHEN ID_TIPO_PROPIEDAD = 'E' THEN 'Parcela con casa'
        ELSE 'Otro'
    END AS "DESCRIPCION",
    
    LPAD(REPLACE(TO_CHAR(AVG(VALOR_GASTO_COMUN), '$999,999'),',','.'),20) AS "PROMEDIO GASTO COMUN",
    COUNT(ID_TIPO_PROPIEDAD) AS "CANTIDAD PROPIEDADES",
    LPAD(REPLACE(TO_CHAR(AVG(VALOR_ARRIENDO), '$99,999,999'),',','.'),25) AS "PROMEDIO VALOR ARRIENDO"
    
FROM PROPIEDAD
GROUP BY ID_TIPO_PROPIEDAD
HAVING AVG(VALOR_ARRIENDO) >= &VALOR_MINIMO
ORDER BY ID_TIPO_PROPIEDAD ASC, AVG(VALOR_ARRIENDO) DESC;